<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYwhwvwr\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYwhwvwr/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYwhwvwr.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYwhwvwr\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYwhwvwr\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ywhwvwr',
    'container.build_id' => '059e58c3',
    'container.build_time' => 1520542190,
));
