<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYviy5p8\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYviy5p8/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYviy5p8.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYviy5p8\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYviy5p8\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Yviy5p8',
    'container.build_id' => 'd55edd41',
    'container.build_time' => 1521736874,
));
